server/config/connection.js
=> made veritiDB connection

server/schemas/index.js
leave apollo-schemas branch open for @IndigoFobes to work on typeDefs and resolvers
=> typeDefs and resolver route

server/models/Category.js, server/schemas/resolvers.js, server/schemas/typeDefs.js
Just basic setup for the schema files
=> Updates to Typedefs and Resolvers, and minor update to Category model

client/public/index.html, client/src/App.jsx, client/src/components/Filter.jsx, client/src/components/Footer.jsx, tailwind.config.js
added multi-select dropdown 
added footer
=> filter + footer

client/package.json, client/src/utils/auth.js, server/package.json, server/utils/auth.js
Added auth functionality in utils folder of client/server
Added dependency in package.json.
=> Added dependnecy & auth classes

server/models/Donation.js, server/models/User.js, server/schemas/resolvers.js, server/schemas/typeDefs.js
Save and Unsave charity info to user database.
=> Updated resolvers and minor changes in models.

server/schemas/resolvers.js, server/schemas/typeDefs.js
Removed portfolio dependency
Added login code
=> Login functionality server

client/src/App.jsx, client/src/components/Card.jsx, client/src/components/Dashboard.jsx, client/src/components/Header.jsx
=> built dashboard

server/models/Donation.js, server/models/index.js, server/schemas/index.js, server/schemas/resolvers.js, server/schemas/typeDefs.js
Added index.js file on models
Added code to resolved running graphql issue
=> resoved running graphql error

server/schemas/resolvers.js, server/schemas/typeDefs.js, server/seeders/seed.js
Resolved seeding issue
Updated add user method in resolver file
added users query in resolver
Updated type query in typedefs
Execute login and add user functionality on graphql server
=> User seed jwt verification on graphql

server/models/Charity.js, server/schemas/typeDefs.js, server/seeders/categorySeeds.json, server/seeders/charitySeeds.json
I put our actual charity and category data into their corresponding json files
=> New seeds with real data.

server/seeders/charitySeeds.json
Yeesh, y'all I thought the images made it into that commit, but I totally didn't add those last night. Here are the images added to the seeder.
=> This commit actually has the images.

server/schemas/resolvers.js, server/schemas/typeDefs.js
updated typeDef language to match resolver,
removed Category model from resolver
=> Debugged Save/Unsave Charity Mutation

client/src/components/Login.jsx, client/src/pages/LoginSignup.js, client/src/utils/auth.js
Handle error message if user enter incorrect credential
Redirect login page to explore
Handle logout functionality
=> Redirect Login page to explore page

client/src/components/CardNoCTA.jsx, client/src/components/Header.jsx, server/seeders/charitySeeds.json
- Added cards to landing page
- mapped through data
- styled* @mnghinguyen I didn't media query so this is something you may need to work with tonight! I didn't want to do too much to your pre-existing code.
=> Landing page cards rendered and mapped

client/src/components/Card.jsx, client/src/utils/auth.js, client/src/utils/mutations.js
- Converted link to button (save)
- Called save_charity mutation when user click to save button and charity is saved of that user.
- Added localstorage for saved charity id and get charity id when user reloading page.
- Cleared local storage
=> Save chairity explore feature

client/src/components/Card.jsx, client/src/components/CardSaved.jsx, client/src/components/PortfolioComp.jsx, client/src/utils/auth.js, client/src/utils/mutations.js, client/src/utils/queries.js, server/schemas/typeDefs.js
Below things I have added in this PR.
Removed local storage functionality from explore tab and Handle button text based on logged user charities data. 
Render charities data on card based on user in Portfolio component
When user click on unsaved button,  charity is deleted from user in backed and frontend and also changed saved  button status  on explore tab.
=> Save unsave charities functionality explore & portfolio page

client/src/components/DownloadXlsx.jsx, client/src/utils/queries.js, package-lock.json, server/schemas/resolvers.js
- updated resolvers with proper populate path for donation query (can now access subqueries)
- finished xlsx feature - charity, name, ein, id, donationAmount, donationDate
=> Xlsx feature complete!

client/src/components/Card.jsx, client/src/components/CardNoCTA.jsx, client/src/pages/Home.js
Used media queries to change font sizes and margins(?) as screen size changes... Had a bit of trouble getting the card as a whole to scale down, because it wanted to mess with the image. But this looks a bit better to me!
=> Media query

README.md
This is the start to the readme. Would love input on hopes for future development. Also ideas on Licensing, if we want that. And finally, I am going to wait until the app is good to deploy to put images in readme!
=> Readme started. Still missing some items.

client/src/components/Card.jsx, client/src/components/CardRec.jsx, client/src/components/CardSaved.jsx, client/src/components/PortfolioComp.jsx, client/src/components/Recommendations.jsx, client/src/components/Summary.jsx, client/src/pages/Portfolio.js, client/src/utils/queries.js, server/schemas/resolvers.js, server/seeders/charitySeeds.json
Added random functionality to randomly display charities data on card.
=> Portfolio use state summary recs

client/src/components/Card.jsx, client/src/components/CardSaved.jsx, client/src/components/Filter.jsx, client/src/components/PortfolioComp.jsx, client/src/pages/Explore.js, client/src/pages/Portfolio.js, server/models/Donation.js
Removed commented code from files.
=> Removed commented code

client/src/utils/auth.js, server/.env, server/config/connection.js
Recommendations section is not displaying on portfolio page - Resolved
Redirect to main page once user successfully login to application
Resolved - User can not redirect explore tab directly without login
Once logged in - user is redirecting to explore instead of login page
=> Recommendations_Auth_Problem_feature

.gitignore, client/.gitignore, client/src/components/CheckoutForm.jsx, server/.env
added stripe redirect after payment
trying one more time to load .env without showing to github
=> Stripe reload
